enum RenderSign{EMPTY,
		   WALL,
		   SNAKEHEAD,
		   SNAKEBODY,
		   TREASURE,
		   TRAP,
		   PARTICLE1,
		   PARTICLE2,
		   PARTICLE3,
		   PARTICLE4,
		   PARTICLE1_ON_WALL,
		   PARTICLE2_ON_WALL,
		   PARTICLE3_ON_WALL,
		   PARTICLE4_ON_WALL};
enum Duration{UP, 
			  DOWN, 
			  LEFT, 
			  RIGHT};